global:
  scrape_interval: 5s  # Thu thập dữ liệu thường xuyên hơn

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'chatbot'
    static_configs:
      - targets: ['chatbot:8000']
